// autogenerated by reconstant - do not edit!
package generated_constants

// constants
const SomeConstant = "this is a constant string"
const OtherConstant = 42

// enums
const (
	A = iota
	B
	C
)

const (
	Foo = iota
	Bar
)

