# autogenerated by reconstant - do not edit!
from enum import Enum

# types

# constants
SOME_CONSTANT = "this is a constant string"
OTHER_CONSTANT = 42

# enums
class SomeEnum(Enum):
	A = 5
	B = 6
	C = 7

class OtherEnum(Enum):
	FOO = 0
	BAR = 1

