// autogenerated by reconstant - do not edit!
package generated_constants

// types
type CommandType int

// constants
const SomeConstant = "this is a constant string"
const OtherConstant = 42

// enums
const (
	A CommandType = iota + 5
	B
	C
)

const (
	Foo  = iota 
	Bar
)

